### ISSUE TITLE
Feed links in meta_block are not generated from settings.json

### ISSUE THREAD

**Issue by saerdnaer** [thomersch/Mikrowelle-OS#17]
See https://github.com/thomersch/Mikrowelle-OS/blob/master/templates/meta_block.tpl for hardcoded HTML.

**Comment by thomersch** [comment]
Added automatic feed link generation in base template: https://github.com/thomersch/Mikrowelle-OS/commit/44b1ae7ba8695429cf36f1d77c39d73123ad5e09
